### ISSUE TITLE
MOCKUP

### ISSUE THREAD

**Issue by Seyha-Soeurn** [Chamsmey/2022-QUIZE-APP-G16#3]
Design app

**Comment by Chamsmey** [comment]
![Create question](https://user-images.githubusercontent.com/90992869/150512945-74d6f765-85dc-4267-965a-f899fc252a6a.png)
![Home page](https://user-images.githubusercontent.com/90992869/150512956-4eaabacf-4a0e-4f4b-afeb-7f6e8229b932.jpg)
![Result](https://user-images.githubusercontent.com/90992869/150512964-02faaf8c-0e60-41c1-9641-9d84eb32bb62.jpg)
![Result](https://user-images.githubusercontent.com/90992869/150512967-09a633cf-0b92-47f0-a117-0ef35ee30536.png)

**Comment by Chamsmey** [comment]
![Home page](https://user-images.githubusercontent.com/90992869/150513261-fb1b0344-5cc3-460b-a3f4-a41bdaf05688.jpg)
![Quiz](https://user-images.githubusercontent.com/90992869/150513264-2051f9e0-75fc-4200-ac27-30f0763c4052.jpg)
![Create question](https://user-images.githubusercontent.com/90992869/150513256-9365d3d4-0d51-4433-82de-938ec527b11e.png)
![Result](https://user-images.githubusercontent.com/90992869/150513268-fefd2e0b-6227-451d-a4b6-994fa0c80a86.png)
